### ISSUE TITLE
Met "can't open file 'app.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by chunyunchen** [openshift/django-ex#5]
1) Login openshift and create project for the user

$ osc login --server=$master -u $user -p $password
$ osc new-project test

2) Create imageStream

$ osc create -f image-streams-centos7.json
(the file "image-streams-centos7.json" is same with https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json)

3) Login openshift in web console

4) Create application in console

"Create.." -> Input repo url "https://github.com/openshift/django-ex" -> "Next" -> Select a builder image "python:latest" -> finish create

5) Start a build in webconsole

Browse -> Builds -> "Start Build"

6) Wait build to complete and keep an eye on  the log of pod

$ osc get pod
$ osc logs django-ex-1-c4x9k

**************log messages as below******************

python manage.py migrate --noinput
Operations to perform:
  Synchronize unmigrated apps: messages, staticfiles, debug_toolbar
  Apply all migrations: sessions, auth, admin, welcome, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
  Applying welcome.0001_initial... OK
Metadata-Version: 2.0
Name: gunicorn
Version: 19.3.0
Summary: WSGI HTTP Server for UNIX
Home-page: http://gunicorn.org
Author: Benoit Chesneau
Author-email: benoitc@e-engura.com
License: MIT
Location: /opt/openshift/src/.local/lib/python3.3/site-packages
Requires: 
python: can't open file 'app.py': [Errno 2] No such file or directory

**Comment by rhcarvalho** [comment]
The problem here is missing environment variables used by [sti-python](https://github.com/openshift/sti-python/tree/master/3.3), namely `APP_MODULE` or `APP_FILE` to run your application, and `APP_CONFIG` for passing configuration to gunicorn. If none of the first two are defined, it defaults to trying to run a file called `app.py`.

Looking at the create flow, I see there is a way to add environment variables before creating the app, but those variables I mentioned above are not documented well.

One improvement we could make is to fail the build if we will not know how to run the app later. @mfojtik @bparees @soltysh what do you think?

FWIW this problem is not specific to django-ex, but general to any Python project using sti-python.

**Comment by mfojtik** [comment]
@rhcarvalho can we attempt to do some smart detection what file is present instead of defaulting to app.py?

**Comment by rhcarvalho** [comment]
@mfojtik we could detect that this is a Django project, and serve it with gunicorn if gunicorn was part of your requirements, or with ./manage.py runserver if gunicorn is not there.

**Comment by mfojtik** [comment]
@rhcarvalho @soltysh that seems strange to me... i'm not python user but I would expect something consistent with Ruby, where:

1. we check if you have gunicorn|microwhiskey|whatever server installed and use that to run you app
2. if not, we default the 'django run' and run the internal django server with message that warn you about you running in 'development' server mode
3. if you set APP_MODULE/APP_FILE 1) and 2) are invalid and we run that app/module instead
4. if none of the above is true, we error out

There should be **no** obligation for users to set some required env variable in order to run python application. We should provide some sane default and autodetection that will work for 80% of use-cases. If you do something special, then you can still write your own .sti/bin/run script.

**Comment by soltysh** [comment]
+1 for adding django autodetection in sti-python, I thought this was already agreed before.
@mfojtik for the defaults, ruby is maybe different with python the problem is users can name their apps whatever they want. I took exactly the same solution as we have in v2 (namely `app.py`), which can be changed with `APP_FILE`. Although running apps with dev server is **strongly** discouraged I'm ok with having this as fall-back option.

**Comment by mfojtik** [comment]
@soltysh so APP_FILE defaults to 'app.py'? that seems reasonable to me.

**Comment by mfojtik** [comment]
@soltysh app.py should be the last attempt before we fail with error message "Sorry, we are unable to run you. You have to provide foo, bar, ...."

**Comment by soltysh** [comment]
@mfojtik and that's how it's done right now, `app.py` is the last option if everything else fails.

**Comment by bparees** [comment]
agree with the flow @mfojtik proposed.

As for @rhcarvalho's suggestion that we fail the build if we can't run it later, i like that also, but it likely means duplicating a bunch of logic between the assemble and run scripts.

**Comment by soltysh** [comment]
The other problem with @rhcarvalho solution is that those env used for running are specified at Deployment, which we don't know anything about at build time, so we'd have to duplicate those vars as well in both places for builds to be aware of them and for deployments to actually use them.

**Comment by rhcarvalho** [comment]
@chunyunchen this flow has been fixed, thank you.
