### ISSUE TITLE
allowed_hosts

### ISSUE THREAD

**Issue by jfmatth** [openshift/django-ex#91]
In Openshift2 I used to set allowed_hosts to an environment variable called OPENSHIFT_APP_DNS, but now I notice that you have used * in it's place.

Do we think this is safe since we are in a dedicated container now?

Just wanted to check.

thanks,

**Comment by bparees** [comment]
no, it's that we don't know the host you're going to expose the application on.  it's determined by the route you create, and in turn the route's hostname is determined by the project name and other dynamic pieces (unless you control the DNS and can set an explicit route name).

you are to some degree protected by the router in that a request is unlikely to get to your app unless you defined a route that points to it and someone sent a request to that route w/ the proper host header, but that is not a guarantee.  If you really care about this, you will want to set the value yourself.  But the value to set it to is not available as an env variable inside the application because, again, in v3 the route is decoupled from the application, unlike in v2 when they were tightly coupled.

**Comment by jfmatth** [comment]
Thanks Ben, that makes sense.
